// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromoSpark.Infrastructure.Data;

#nullable disable

namespace PromoSpark.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250113230236_UpdatedDB")]
    partial class UpdatedDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromoSpark.Domain.Entities.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("AllowedPlatforms")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreativeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfWinners")
                        .HasColumnType("integer");

                    b.Property<decimal>("RewardPool")
                        .HasColumnType("numeric");

                    b.Property<string>("SongUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreativeId");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a271f15-41c5-4c70-849b-c19aa2e02e4e"),
                            AllowedPlatforms = new[] { 2, 1 },
                            CreatedAt = new DateTime(2025, 1, 13, 23, 2, 34, 681, DateTimeKind.Utc).AddTicks(6650),
                            CreativeId = new Guid("022dab84-9b44-42c6-8bec-ee870fd2e7f8"),
                            Deadline = new DateTime(2025, 1, 23, 23, 2, 34, 680, DateTimeKind.Utc).AddTicks(7635),
                            Description = "Submit your best dance video to win!",
                            NumberOfWinners = 3,
                            RewardPool = 1000m,
                            SongUrl = "https://example.com/song1",
                            Status = 2,
                            Title = "Dance Challenge 2025"
                        });
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("PlatformPostUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RewardAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6024f119-4f1e-49b6-9344-f0efbf5976c2"),
                            Caption = "My best dance moves!",
                            ChallengeId = new Guid("1a271f15-41c5-4c70-849b-c19aa2e02e4e"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 2, 34, 682, DateTimeKind.Utc).AddTicks(4976),
                            IsVerified = true,
                            ParticipantId = new Guid("8cb79fa2-df52-4c32-8ea0-d8179164d7f2"),
                            Platform = 2,
                            PlatformPostUrl = "https://tiktok.com/post1",
                            VideoUrl = "https://example.com/video1"
                        },
                        new
                        {
                            Id = new Guid("56f2ffc5-7826-4816-8e38-b7b76f0b41d9"),
                            Caption = "Another submission!",
                            ChallengeId = new Guid("1a271f15-41c5-4c70-849b-c19aa2e02e4e"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 2, 34, 682, DateTimeKind.Utc).AddTicks(5647),
                            IsVerified = false,
                            ParticipantId = new Guid("8cb79fa2-df52-4c32-8ea0-d8179164d7f2"),
                            Platform = 1,
                            PlatformPostUrl = "https://instagram.com/post2",
                            VideoUrl = "https://example.com/video2"
                        });
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayoutAccountNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SocialMediaLinks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8cb79fa2-df52-4c32-8ea0-d8179164d7f2"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 2, 34, 678, DateTimeKind.Utc).AddTicks(8809),
                            Email = "participant@example.com",
                            FullName = "John Doe",
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword1",
                            Role = 1,
                            WalletBalance = 0m
                        },
                        new
                        {
                            Id = new Guid("022dab84-9b44-42c6-8bec-ee870fd2e7f8"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 2, 34, 678, DateTimeKind.Utc).AddTicks(9845),
                            Email = "creative@example.com",
                            FullName = "Jane Smith",
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword2",
                            Role = 2,
                            WalletBalance = 100.50m
                        },
                        new
                        {
                            Id = new Guid("4e1b7d4c-33b6-47d2-b36b-95434a9d3e67"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 2, 34, 678, DateTimeKind.Utc).AddTicks(9851),
                            Email = "admin@example.com",
                            FullName = "Admin User",
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword3",
                            Role = 3,
                            WalletBalance = 0m
                        });
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Challenge", b =>
                {
                    b.HasOne("PromoSpark.Domain.Entities.User", "Creative")
                        .WithMany()
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creative");
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Submission", b =>
                {
                    b.HasOne("PromoSpark.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromoSpark.Domain.Entities.User", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Challenge", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
