// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromoSpark.Infrastructure.Data;

#nullable disable

namespace PromoSpark.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250113234410_Updated")]
    partial class Updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromoSpark.Domain.Entities.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("AllowedPlatforms")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreativeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfWinners")
                        .HasColumnType("integer");

                    b.Property<decimal>("RewardPool")
                        .HasColumnType("numeric");

                    b.Property<string>("SongUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreativeId");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b096b84-0f1b-4f20-9c31-0e0c60acb2a4"),
                            AllowedPlatforms = new[] { 2, 1 },
                            CreatedAt = new DateTime(2025, 1, 13, 23, 44, 8, 597, DateTimeKind.Utc).AddTicks(7467),
                            CreativeId = new Guid("e5d4549f-0607-4716-9818-e6c6a6bb33a0"),
                            Deadline = new DateTime(2025, 1, 23, 23, 44, 8, 596, DateTimeKind.Utc).AddTicks(8031),
                            Description = "Submit your best dance video to win!",
                            NumberOfWinners = 3,
                            RewardPool = 1000m,
                            SongUrl = "https://example.com/song1",
                            Status = 2,
                            Title = "Dance Challenge 2025"
                        });
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("PlatformPostUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RewardAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d40cb34c-92b5-4a77-8750-bc10cb661b5d"),
                            Caption = "My best dance moves!",
                            ChallengeId = new Guid("0b096b84-0f1b-4f20-9c31-0e0c60acb2a4"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 44, 8, 598, DateTimeKind.Utc).AddTicks(6276),
                            IsVerified = true,
                            ParticipantId = new Guid("175a0cdd-425e-4098-9fce-b99b408471e7"),
                            Platform = 2,
                            PlatformPostUrl = "https://tiktok.com/post1",
                            VideoUrl = "https://example.com/video1"
                        },
                        new
                        {
                            Id = new Guid("0d03a999-f26b-47eb-ac93-f3072e501c2b"),
                            Caption = "Another submission!",
                            ChallengeId = new Guid("0b096b84-0f1b-4f20-9c31-0e0c60acb2a4"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 44, 8, 598, DateTimeKind.Utc).AddTicks(6996),
                            IsVerified = false,
                            ParticipantId = new Guid("175a0cdd-425e-4098-9fce-b99b408471e7"),
                            Platform = 1,
                            PlatformPostUrl = "https://instagram.com/post2",
                            VideoUrl = "https://example.com/video2"
                        });
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayoutAccountNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SocialMediaLinks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("175a0cdd-425e-4098-9fce-b99b408471e7"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 44, 8, 594, DateTimeKind.Utc).AddTicks(8250),
                            Email = "participant@example.com",
                            FullName = "John Doe",
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword1",
                            Role = 1,
                            WalletBalance = 0m
                        },
                        new
                        {
                            Id = new Guid("e5d4549f-0607-4716-9818-e6c6a6bb33a0"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 44, 8, 594, DateTimeKind.Utc).AddTicks(9320),
                            Email = "creative@example.com",
                            FullName = "Jane Smith",
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword2",
                            Role = 2,
                            WalletBalance = 100.50m
                        },
                        new
                        {
                            Id = new Guid("26fda9be-7ccb-4c38-a720-ef0ed9320c3f"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 44, 8, 594, DateTimeKind.Utc).AddTicks(9328),
                            Email = "admin@example.com",
                            FullName = "Admin User",
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword3",
                            Role = 3,
                            WalletBalance = 0m
                        });
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Challenge", b =>
                {
                    b.HasOne("PromoSpark.Domain.Entities.User", "Creative")
                        .WithMany()
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creative");
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Submission", b =>
                {
                    b.HasOne("PromoSpark.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromoSpark.Domain.Entities.User", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Challenge", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
