// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromoSpark.Infrastructure.Data;

#nullable disable

namespace PromoSpark.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250113233101_UpdatedD")]
    partial class UpdatedD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromoSpark.Domain.Entities.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("AllowedPlatforms")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreativeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfWinners")
                        .HasColumnType("integer");

                    b.Property<decimal>("RewardPool")
                        .HasColumnType("numeric");

                    b.Property<string>("SongUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreativeId");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f973e27d-dc09-492e-a0cb-32a9c3abc2e2"),
                            AllowedPlatforms = new[] { 2, 1 },
                            CreatedAt = new DateTime(2025, 1, 13, 23, 30, 59, 567, DateTimeKind.Utc).AddTicks(4284),
                            CreativeId = new Guid("f3b75726-55c8-45ee-b5dc-8fa99485579b"),
                            Deadline = new DateTime(2025, 1, 23, 23, 30, 59, 566, DateTimeKind.Utc).AddTicks(4747),
                            Description = "Submit your best dance video to win!",
                            NumberOfWinners = 3,
                            RewardPool = 1000m,
                            SongUrl = "https://example.com/song1",
                            Status = 2,
                            Title = "Dance Challenge 2025"
                        });
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("PlatformPostUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RewardAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f57a28bf-a632-42b6-a843-948804d2c73b"),
                            Caption = "My best dance moves!",
                            ChallengeId = new Guid("f973e27d-dc09-492e-a0cb-32a9c3abc2e2"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 30, 59, 568, DateTimeKind.Utc).AddTicks(3009),
                            IsVerified = true,
                            ParticipantId = new Guid("abcdabf7-a9bb-4531-8c58-188f258c3146"),
                            Platform = 2,
                            PlatformPostUrl = "https://tiktok.com/post1",
                            VideoUrl = "https://example.com/video1"
                        },
                        new
                        {
                            Id = new Guid("83ac48a8-e7c5-41de-b6a3-f0029f34dfa6"),
                            Caption = "Another submission!",
                            ChallengeId = new Guid("f973e27d-dc09-492e-a0cb-32a9c3abc2e2"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 30, 59, 568, DateTimeKind.Utc).AddTicks(3677),
                            IsVerified = false,
                            ParticipantId = new Guid("abcdabf7-a9bb-4531-8c58-188f258c3146"),
                            Platform = 1,
                            PlatformPostUrl = "https://instagram.com/post2",
                            VideoUrl = "https://example.com/video2"
                        });
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayoutAccountNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SocialMediaLinks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abcdabf7-a9bb-4531-8c58-188f258c3146"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 30, 59, 564, DateTimeKind.Utc).AddTicks(5372),
                            Email = "participant@example.com",
                            FullName = "John Doe",
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword1",
                            Role = 1,
                            WalletBalance = 0m
                        },
                        new
                        {
                            Id = new Guid("f3b75726-55c8-45ee-b5dc-8fa99485579b"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 30, 59, 564, DateTimeKind.Utc).AddTicks(6385),
                            Email = "creative@example.com",
                            FullName = "Jane Smith",
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword2",
                            Role = 2,
                            WalletBalance = 100.50m
                        },
                        new
                        {
                            Id = new Guid("79f30a2d-c7c0-4d00-aa05-b5d7ee235f98"),
                            CreatedAt = new DateTime(2025, 1, 13, 23, 30, 59, 564, DateTimeKind.Utc).AddTicks(6392),
                            Email = "admin@example.com",
                            FullName = "Admin User",
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword3",
                            Role = 3,
                            WalletBalance = 0m
                        });
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Challenge", b =>
                {
                    b.HasOne("PromoSpark.Domain.Entities.User", "Creative")
                        .WithMany()
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creative");
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Submission", b =>
                {
                    b.HasOne("PromoSpark.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromoSpark.Domain.Entities.User", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("PromoSpark.Domain.Entities.Challenge", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
